# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/fresh-container
  ldflags:
    - -X=github.com/flavio/fresh-container/pkg/fresh_container.Version={{.Version}}
    - -X=github.com/flavio/fresh-container/pkg/fresh_container.BuildDate={{.Date}}
    - -X=github.com/flavio/fresh-container/pkg/fresh_container.Tag={{.Tag}}
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
archives:
- format_overrides:
  - goos: windows
    format: zip
  wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
